version: 1

env:
  - BACKREST_BUILD_VERSION={{.Version}}

before:
  hooks:
    - go mod tidy
    - pnpm --prefix webui install
    - sh -c "GOOS=linux BACKREST_BUILD_VERSION={{.Version}} go generate ./..."
    - sh -c "GOOS=windows BACKREST_BUILD_VERSION={{.Version}} go generate ./..."

builds:
  - id: backrest
    main: ./cmd/backrest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"

  - id: backrestmon
    main: ./cmd/backrestmon
    binary: backrest-windows-tray
    env:
      - CGO_ENABLED=1
    ldflags: "-H=windowsgui"
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    allow_different_binary_count: true
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

dockers:
  - image_templates:
      - dr.xczns.top:58808/backrest:latest
      - dr.xczns.top:58808/backrest:{{ .Tag }}
    dockerfile: Dockerfile.alpine
    use: buildx
    goarch: amd64
    goos: linux
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    skip_push: false

release:
  github:
    owner: xcz-ns
    name: backrest

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"