name: Backrest 构建

on:
  push:
    tags:
      - "*"  # 匹配所有 tag 推送
  workflow_dispatch:  # 手动触发工作流

permissions:
  contents: write  # 允许工作流写入发布内容

jobs:
  tagged-release:
    name: 标签构建发布
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码（Checkout）
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史（便于生成版本信息）

      - name: 设置 QEMU（用于多架构构建）
        uses: docker/setup-qemu-action@v3

      - name: 设置 Go 开发环境
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 设置 pnpm 包管理器
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 执行 GoReleaser 发布
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.26.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: dist/*

  tagged-release-installers:
    name: 安装包生成发布
    runs-on: ubuntu-latest
    needs: tagged-release  # 等待前一个任务完成

    steps:
      - name: 检出代码（Checkout）
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: dist

      - name: 生成安装程序
        run: |
          mkdir -p dist-installers
          ./scripts/generate-installers.sh ./dist-installers

      - name: 上传安装包到 Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist-installers/Backrest-setup-x86_64.exe
      #      ./dist-installers/Backrest-setup-arm64.exe
