name: Backrest 构建发布（官方 Action 方案）

on:
  push:
    tags:
      - '*'   # 监听所有 Tag 推送触发
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write  # 允许写入 Release 内容

jobs:
  build-and-release:
    name: 构建并发布 Release
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史（方便版本信息）

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: 设置 Node.js 环境（如果需要）
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 设置 pnpm 包管理器（如果需要）
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 构建二进制文件
        run: |
          # 这里替换为你的实际构建命令
          go build -o dist/backrest-linux-amd64 ./cmd/backrest
          # 如果有多平台构建，可以添加相应命令

      - name: 打包构建产物（示例为 zip）
        run: |
          mkdir -p dist
          cd dist
          zip backrest-linux-amd64.zip backrest-linux-amd64

      - name: 创建 GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传 Release 资产
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/backrest-linux-amd64.zip
          asset_name: backrest-linux-amd64.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
